### PR TITLE
fixes #14: crop api now matches pillow api

### LINKED ISSUE #14: Bug in crop
in image_process.py line 65, left comes in front of top

 `return i.crop((int(t), int(l), int(r), int(b)))`
should be instead
 `return i.crop((int(l), int(t), int(r), int(b)))`

### PR DESCRIPTION
**Pull request by Ecno92**

### CODE REVIEW

**Comment by MinchinWeb** [comment]
@Ecno92 something like this changes the public API, and so should probably bump the version number to 2.0.0, rather than 1.4.0...

**Comment by Ecno92** [comment]
@MinchinWeb 
Thanks for the feedback.
It is not unique to not raise the major version number in case of backwards incompatible changes. (Examples: Django, PHP)
I'll consider to raise the version number to something different once we are approaching a next release.

**Comment by MinchinWeb** [comment]
Looking at my assumptions, I realize I'm a big fan of [Semantic Versioning](https://semver.org/) (which says to increase the major version number on backwards incomparable changes). It's particularly helpful as I've started dealing with more and more packages on a single project.

**Comment by Ecno92** [comment]
@MinchinWeb fixed :) 164549a6aee7bd7c15d0978532fa6d9069a72a32

**Comment by MinchinWeb** [comment]
@Ecno92 awesome! thanks.

**Pull request merged**
